<Project Sdk="MSTest.Sdk/4.0.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="MSTestSettings.fs" />
    <Compile Include="Test1.fs" />
  </ItemGroup>

</Project>
